[quote.epigraph, , 1 Tesalonicenses 5:21]
____
Examinadlo todo; retened lo bueno.
____

== Vida y Cartas de Samuel Crisp

Samuel Crisp, antes de unirse a la Sociedad de Amigos, residía en Norfolk.
Fue educado en la universidad y tomó la orden de
diácono en la iglesia de Inglaterra (así llamada);
después de lo cual ofició como cura parroquial, y por un tiempo muy corto,
como capellán en una familia privada.

En el año 1700, residiendo entonces en Londres y con unos treinta años de edad,
se convenció de la verdad que profesaban los Amigos,
de la manera que se describe en su primera carta más abajo.
Poco después, fue contratado como asistente de Richard Scoryer,
un Amigo que tenía un gran internado en Wandsworth.
No permaneció por mucho tiempo en este estado,
y posteriormente abrió una escuela por su cuenta en Stepney, cerca de Londres.

De una obra suya titulada [.book-title]#The Present State of Quakerism in England#,^
footnote:[El Estado Actual del Cuaquerismo en Inglaterra.]
obtenemos los siguientes detalles y observaciones,
relativos a su salida de la comunión con la iglesia establecida,
y de los puestos que ocupó en ella:

[quote]
____
En cuanto a mi salida de la Iglesia de Inglaterra,
Dios es mi testigo de que lo hice en obediencia pura
a las convicciones de mi propia mente;
y la paz que a menudo he sentido en mi pecho en respuesta a ello,
es más de lo que puedo expresar.
He tenido una gran y abundante recompensa del Señor por lo que he hecho en este asunto.
Deseo temer a Dios,
y lamento de corazón haber pasado tanto tiempo en
las vanidades y pequeñeces de este mundo pecaminoso;
creyendo cosas sin examinarlas,
dejándome llevar por los intereses temporales y siguiendo
los prejuicios de mi educación.

Es cierto que sólo estaba en la orden de diácono,
y bendigo a Dios por no haber llegado más lejos en tales órdenes.
En ese entonces yo pretendía predicar,
y podía armar un discurso de una hora con algo que tomaba de otros,
y con algo que había leído de la Biblia,
y llenaba los vacíos con las oscuras concepciones
de mi propio cerebro--y ese era mi evangelio.
Podía hablar mucho de Cristo, del cielo y del infierno, y ensalzar mucho las Escrituras,
las cuales, sin embargo, eran un libro sellado para mí; pues aunque las leía a menudo,
en público y en privado, aun así mi mente estaba fuera,
y como no esperaba en silencio al Espíritu Santo que las había dado,
no conocía las Escrituras, ni experimentaba el poder de Dios.
Así reinaba en mí el poder de la muerte y de las tinieblas, en ese entonces.

Como diácono tenía que estar al cuidado de las almas (como lo llaman ellos),
pero era un médico nulo.
En efecto, sabía que había completado mi tiempo en la universidad,
como hacen los aprendices de un oficio,
y que había pasado el examen y la ceremonia de ordenación--y creía que con eso bastaba;
pero no sabía nada de un llamamiento o nombramiento
directo de Dios para la obra del ministerio.
Yo estaba al cuidado de dos parroquias que el obispo de la diócesis me había encomendado,
pero nunca recibí un llamamiento de Dios para ir a predicar a ese pueblo.
Así que yo era como aquellos profetas de los que habla Jeremías, capítulo 23:21,
que corrían antes de ser enviados, y por eso no podían beneficiar al pueblo en absoluto.
En realidad,
yo era un fanático supersticioso--una pobre criatura
oscura--un asalariado--un líder ciego de ciegos.
Esperaba treinta libras al año por predicar--ese era mi salario;
y era tan bruto en mi entendimiento, que si alguien cuestionaba mi comisión,
sabía que tenía un pequeño pedazo de papel para mostrarles, que yo llamaba mis órdenes,
si eso los satisfacía.

Y sin embargo, Dios no se quedó sin testigo,
porque en medio de toda esta oscuridad e ignorancia, puedo decir con toda seguridad,
que había una medida de sinceridad en mí. A menudo se levantaban en mí buenos deseos,
fervientes clamores y suspiros, pues anhelaba conocer verdaderamente al Señor y servirle,
y ver Su gloria, y experimentar la paz, gozo, salud,
reposo y salvación de mi alma antes de salir del escenario de este mundo,
para así poder vivir con Él en ese mundo que no tendrá fin,
cuando el tiempo aquí se hubiera acabado.
Y Dios no estaba inconsciente de los dolores de parto de Su propia semilla en aquel día,
porque bendito sea Su nombre,
Él oyó los gemidos de Ella bajo una gran cantidad de basura, y reveló a Su hijo en mí,
ante Cuyo resplandor se dispersan las nubes y huyen las sombras.
¡Qué la consciencia de Su bondad y tierna misericordia nunca se aparte de mí,
mientras tenga una hora de vida o un minuto de aliento en este mundo!
Al Dios que tuvo compasión del Israel antiguo, cuando habitaban en tierra extraña,
donde los egipcios y el faraón los oprimían con mucha,
cruel y dura servidumbre--a ese mismo Dios le atribuyo mi liberación;
el único digno de ser alabado,
magnificado y adorado por todos los que hacen mención de Su nombre.
Él se acordó de nosotros cuando estábamos en problemas, angustia y profunda aflicción,
estando dispersos en las oscuras y estériles montañas como ovejas sin pastor,
vagando de montaña en montaña, y de una forma y vacía profesión de religión a otra.
Ahí nos encontró y Su ojo se compadeció de nosotros, y dijo a los huesos secos:
"`¡Vivan!`"; porque para siempre es Su misericordia.
____

El oficio de capellán en una familia privada (en
el que parece que sólo permaneció diez días),
resultó particularmente molesto e insatisfactorio;
y es probable que las circunstancias relacionadas con dicho oficio fortalecieran,
en grado no pequeño,
su deseo de desvincularse de las formas y ceremonias en las que había sido educado.
Refiriéndose a su situación en ese oficio,
afirma que había tenido que esperar tres o cuatro horas
seguidas para saber cuándo deseaba orar la familia;
y que su tarea no terminaba cuando terminaban los oraciones,
ya que le pedían que esperara y estuviera listo para cuando lo llamaran
de una habitación contigua por donde a menudo pasaban sirvientes y otros,
y que a veces lo habían hecho esperar desde la mañana hasta la noche.
Es probable que hubiera podido sobrellevar esos inconvenientes
hasta que se presentara una designación menos fastidiosa,
si hubiera podido continuar ahí y al mismo tiempo disfrutar paz mental; pero escribe:

[quote]
____
Dejé mi puesto de capellán por un principio puramente de consciencia;
el brillo de la riqueza no pudo mantenerme ahí,
y esto sucedió unos meses antes de conocer al pueblo llamado Cuáqueros,
o de tener el menor pensamiento en ese sentido.
Por un tiempo viví discretamente en Londres, buscando las mejores cosas.
Por ese entonces había un gran ruido con respecto a los Cuáqueros, y George Keith^
footnote:[George Keith era un destacado miembro escocés
de la primitiva Sociedad de Amigos,
que habló y escribió mucho en defensa de los principios y doctrinas de los Cuáqueros,
e incluso sufrió el encarcelamiento por su testimonio de la verdad.
Desgraciadamente, más adelante,
debido a un espíritu inquieto y ambicioso que aspiraba a la preeminencia
en la Sociedad (George Fox había muerto en 1690),
Keith acabó por oponerse abiertamente, primero a individuos específicos, y finalmente,
a toda la Sociedad de Amigos.
Después de intentar primero, establecer su propia sociedad religiosa independiente,
al final se unió a la iglesia de Inglaterra,
fue ordenado sacerdote por el obispo de Londres,
y terminó sus días como perseguidor de la misma sociedad religiosa que antes había defendido.]
(quien acababa de ser ordenado diácono) era la comidilla del pueblo.
Así que,
al encontrarme un día con las obras de Robert Barclay en el estante de una librería,
y sabiendo que era un Cuáquero y un eminente escritor entre ellos,
tuve un gran deseo de leerlas.
Lo hice en el temor de Dios y con mente humilde,
y quedé tan plenamente convencido de la verdad de los principios
de los Cuáqueros (a pesar del clamor del mundo contra ellos),
que desde ese día hasta hoy, nunca he regresado a la iglesia de Inglaterra.
Y aunque en ese momento estaba desprovisto de cualquier sostén externo,
no tenía duda de que el Señor me proporcionaría de algún modo,
una subsistencia idónea en este mundo, que era todo lo que yo deseaba--y así sucedió,
porque en el lapso de unas pocas semanas, fui recomendado para la escuela de Wandsworth,
donde Richard Scoryer necesitaba entonces un asistente.

Pero justo después de convencerme de la verdad,
se presentaron dos ofertas que podrían haberme arrastrado de regreso al mundo.
Una oferta era, leer oraciones en la casa de un boticario en Huntingdon; y la otra,
ser capellán de una tal lady Molesworth, según recuerdo.
En ambos casos había alguna expectativa de mayor distinción,
y ambas ofertas se presentaron antes de que yo oyera hablar de la escuela de Wandsworth,
o supiera algo de ella.
De modo que,
si yo hubiera sido tan codicioso de riquezas como algunos parecen describirme,
habría sofocado mis convicciones y regresado a Egipto.
¡Pero bendito sea Dios,
quien me preservó en ese día y me mantuvo inclinado delante de Él! Confié en
la bondadosa providencia de Aquel que conocía la sinceridad de mi corazón;
y preferí ser pobre y necesitado con una buena consciencia,
que tener todas las riquezas y honores del mundo sin ella.
Había encontrado la perla de gran precio, y sabía que debía venderlo todo para comprarla.
La verdad era mi más grande tesoro;
esa era mi mayor alegría. "`Porque,`" como dice el apóstol, "`nuestra gloria es esta:
el testimonio de nuestra consciencia, que con sencillez y sinceridad de Dios,
no con sabiduría humana, sino con la gracia de Dios, nos hemos conducido en el mundo.`"
____

[.asterism]
'''

[.centered]
=== Cartas de Samuel Crisp

+++[+++Las siguientes tres cartas de Samuel Crisp fueron escritas hacia el año 1702;
la primera y la segunda con motivo de su salida de la iglesia de Inglaterra,
para unirse a la Sociedad de Amigos.
Estas han sido publicadas varias veces juntas como un folleto.
La tercera, aunque muy corta, no carece de valor,
ya que muestra la convicción del escritor,
de que aunque hasta entonces había hecho lo que le exigía
el Señor al unirse en comunión religiosa con los Amigos,
no le proporcionaba motivos para relajar su vigilancia y diligencia en la guerra Cristiana.]

[.embedded-content-document.letter]
--

[.letter-heading]
Carta I

La semana pasada recibí una carta tuya enviada por tu tío Bolton;
había una gran cantidad de expresiones amables en ella,
y también en la de tu hermana Clopton.
Yo me siento muy agradecido con ambos y con toda la familia,
por muchas y repetidas bondades;
y si el cuidado de mi escuela no me hubiera absorbido tanto tiempo,
habría aprovechado la oportunidad para responder
la carta de mi querido amigo antes de ahora,
y por ese motivo mi retraso será más excusable.

La noticia que has oído de mi último cambio es realmente cierta--no puedo ocultarlo,
pues es de lo que me glorío--y no fue ninguna esperanza
de ventaja temporal lo que me indujo a ello,
sino un sincero amor a la verdad y una consideración pura por el bien de mi propia alma.
Tampoco puedo estar suficientemente agradecido con Dios,
por haberme permitido vivir para ver este glorioso día,
y por no haberme cortado en medio de mis pecados
y provocaciones contra Él. Él es paciente con nosotros,
pues no quiere que ninguno perezca, sino que todos lleguemos al arrepentimiento.
Él me ha sacado de las formas y sombras de la religión, y me ha hecho ver,
de manera más ilustre, lo que es la _vida_ y la _sustancia_ de ella,
pues me encontró en cierto grado fiel a esa medida
de luz y conocimiento que Él me había otorgado,
mientras estaba en comunión con la iglesia de Inglaterra.
Y así, recientemente, mientras esperaba humildemente en Él,
Le plació darme a conocer mayores y más profundos misterios de Su reino.
Y puedo decir con seguridad,
que a diario encuentro por experiencia (mientras me mantengo bajo
y retirado hacia ese don puro que Él ha plantado dentro de mí),
que las cosas se me aclaran cada vez más,
y que la verdad brilla y prevalece grandemente sobre el reino de las tinieblas;
y que si yo ahora le diera la espalda a manifestaciones
como estas y me enredara otra vez con el yugo de esclavitud,
ciertamente afligiría al Espíritu Santo,
y Él podría justamente retirar Su tiernas operaciones,
y nunca más regresar a ayudarme ni a consolarme.
Porque Dios no puede ser burlado; la religión es algo muy serio y de peso.
No se debe jugar con el arrepentimiento ni con la salvación,
ni debemos posponer volvernos a Dios hasta nuestro propio tiempo, ocio o conveniencia;
sino que debemos amar y estimar la más pequeña aparición de Cristo,
y no menospreciar el día de las pequeñeces,
sino abrazar la primera oportunidad de seguir a Cristo en cualquiera de Sus mandamientos.
Cuando Él habla, es con tal fuerza y autoridad, que no podemos quedarnos para protestar,
discutir, o hacer preguntas,
porque a menos que seamos tan obstinados como para cerrar nuestros ojos contra el sol,
debemos necesariamente confesar la verdad de Su doctrina y abrazarla inmediatamente.

Por tanto, el haber vivido por varias semanas en Londres,
más privada y retiradamente de lo habitual,
ayunando dos o tres veces a la semana (y algunas veces más),
y dedicando mi tiempo a la lectura de las Escrituras y a la oración a Dios,
fue una buena preparación para que mi mente recibiera
la verdad que Él estaba a punto de darme a conocer.
Lamentaba los errores de mi vida pasada,
y deseaba alcanzar un más excelente grado de santidad
que el que había encontrado en la iglesia de Inglaterra.
En ese retiro religioso, Dios vio las respiraciones de mi alma,
cuán sincero era y cuán rendido estaba a Él cuando
estaba sólo. Yo necesitaba que Él me hiciera libre,
y que le hablara paz y consuelo a mi alma que estaba
afligida y cansada por la carga de mi pecado.
Porque aunque yo me había conformado estrictamente
a las órdenes y ceremonias de la iglesia de Inglaterra,
y me había guardado de caer en pecados grandes o
escandalosos (el temor del Todopoderoso me preservaba),
no tenía ese reposo y satisfacción en mí mismo que tanto deseaba y anhelaba.
Descubrí, tras examinar mi estado y mi condición ante Dios,
que las cosas no estaban bien conmigo.

Yo sabía que tener una conducta sobria y convincente
ante los ojos del mundo era un logro fácil.
Un buen temperamento natural, más la ventaja de una amplia educación,
dotarán a un hombre rápidamente de las habilidades para eso,
de modo que puede llegar a ser considerado santo y muy espiritual,
cuando tal vez todavía esté en cadenas de oscuridad,
en hiel de amargura y en la atadura misma de la iniquidad.
Si ese tipo de justicia hubiera servido, quizás,
yo mismo habría podido quedar tan bien de ese modo como cualquier otro; ¡pero ay!,
rápidamente vi el vacío y la insatisfacción de esas cosas.
En realidad, es una cubierta que no nos protegerá, ni nos esconderá,
de la ira del Todopoderoso cuando venga a juzgarnos.
No es el temperamento natural de un hombre, ni su educación,
lo que lo hace un buen Cristiano; esa no es la justicia que el evangelio requiere,
ni es la "`verdad en lo íntimo`"^
footnote:[Salmo 51:6]
que Dios exige.
El corazón y los afectos deben ser limpiados y purificados
antes de que podamos ser aceptables para Dios;
por lo tanto,
para mí era muerte pensar en descansar en una apariencia formal de santidad,
en la que vi (para mi tristeza) que una gran cantidad de personas se habían envuelto,
y que estaban durmiendo segura y tranquilamente, soñando con la felicidad del paraíso,
como si el cielo ya fuera de ellos y no necesitaran preocuparse más por
la religión. No podía albergar una opinión tan peligrosa como esta,
porque entonces sería tentado a descansar en el camino,
mientras todavía viajaba hacia la Tierra Prometida.

Mientras viví en comunión con la iglesia nacional,
creo que hice un pequeño progreso en la vida santa,
y que mediante la ayuda de Dios debilité a algunos de mis enemigos espirituales.
Le doy gracias a Dios, y en verdad puedo decir, que mientras usé las oraciones de ellos,
lo hice con celo y sinceridad, en Su temor y pavor; pero aun así,
no cesaba de suplicarle fervientemente en privado que me mostrara algo más excelente,
que yo pudiera obtener una victoria completa sobre todos mis deseos y pasiones,
y pudiera perfeccionar la justicia delante Él. Porque yo veía que una
gran cantidad de pecados y debilidades me acompañaban diariamente,
y aunque con frecuencia hacía propósitos de abandonar esos pecados,
las tentaciones eran demasiado fuertes para mí;
de modo que a menudo tenía razones para quejarme
con el apóstol en la amargura de mi alma:
"`¡Miserable de mí! ¿Quién me librará de este cuerpo de muerte?`"^
footnote:[Romanos 7:24]
¿Quién me hará libre y me dará fuerza para triunfar sobre el pecado, el mundo y el diablo?
--¿para complacer a mi Dios en todo, y para que no haya el menor pensamiento,
palabra o movimiento, gesto o acción,
sino lo que es exactamente conforme a Su santísima voluntad,
como si Lo viera de pie delante de mí,
y como si fuera a ser juzgado por Él en el próximo
minuto por el pensamiento de mi corazón? ¡Oh,
divina vida! ¡Oh,
seráfica alma! ¡Ojalá yo pudiera permanecer siempre aquí! Porque aquí no hay reprensiones,
ni dolor, ni arrepentimiento;
pues a la derecha de Dios hay perfecta paz y un río inefable de gozo.
¡Ojalá pudiéramos imitar la vida de Jesús,
y ser completamente preparados para toda buena palabra y obra!
Esta era la frecuente respiración de mi alma a Dios cuando estaba en el campo,
pero más especialmente,
después de haber dejado mi nuevo cargo de capellán
y tomado un alojamiento privado en Londres.
En ese retiro (espero poder decirlo sin jactancia), fui muy devoto y religioso,
y encontré en él gran consuelo y refrigerio del Señor,
quien me dejó ver la belleza de la santidad.
En efecto, la dulzura que se levanta de una vida humillada y llevada a la muerte,
en ese momento fue muy placentera a mi paladar,
y me regocijé en ella más que en todos los deleites y placeres del mundo.

Y entonces,
le plació a Dios mostrarme que si yo en verdad quería vivir
una vida tan estricta y santa como la que adorna el evangelio,
debía dejar la comunión con la iglesia de Inglaterra;
pero yo no sabía aún qué camino coger,
ni a cuál cuerpo de hombres debía unirme que fueran
más ortodoxos y más fieles en sus vidas.
En cuanto a los llamados Cuáqueros,
yo era tan ajeno a ellos que nunca había leído ni uno de sus libros,
ni recuerdo haber conversado con ningún hombre de esa sociedad en toda mi vida.
Creo que había uno en Foxly mientras yo era cura parroquial, pero nunca vi al hombre,
aunque fui varias veces a su casa con el propósito de hablar
con él y sacarlo de su locura y salvaje fanatismo,
como yo entonces ignorantemente pensaba que era.
En cuanto a las creencias y prácticas de los Cuáqueros,
yo sabía que en todas partes se hablaba contra ellas;
porque aquel que quería parecer más inteligente e ingenioso que el resto,
los escogía como objeto de sus bromas y burlas profanas.
De esta manera se divierten los hombres y entretienen a su compañía,
porque un Cuáquero no es sino otro nombre para '`tonto o loco,`' y escasamente
se menciona alguna vez sino con menosprecio y desdén. En cuanto a la burla,
confieso que nunca fui muy amigo de ella; sin embargo, pensaba,
que si todo lo que se les imputaba a los Cuáqueros era cierto,
eran de las peores personas que alguna vez habían aparecido en el mundo,
y me preguntaba cómo podían llamarse a sí mismos cristianos,
pues me habían dicho que ellos negaban los artículos fundamentales de la fe santa,
por la que yo siempre había tenido la más alta veneración y estima.
Y además, yo siempre había vivido a una gran distancia de ese pueblo,
y era muy celoso en la adoración de la iglesia de Inglaterra,
y en toda ocasión hablaba muy honorablemente de ella, e incluso,
estaba contento de sufrir unas pocas inconveniencias por ese motivo.

Un día,
mientras vivía en Londres en la forma retirada y privada de la que acabo de hablar,
caminando muy humildemente ante los ojos de Dios,
y teniendo la oportunidad de reflexionar sobre mi vida pasada,
tuve la oportunidad de entrar en un librería,
y casualmente le eché un vistazo a las obras de Robert Barclay.
Como había oído en el campo que él era un hombre de gran importancia entre los Cuáqueros,
tuve la intención de ver cuáles eran sus principios, y qué defensa podían hacer de ellos;
porque yo realmente pensaba, que este pueblo no podía ser tan tonto y ridículo,
ni sostener opiniones tan horribles, como el autor de [.book-title]#The Snake#`"^
footnote:[Este libro,
"`The Snake in the Grass`" (La Serpiente en la Hierba)
fue publicado anónimamente en el año 1696.
El autor fue empleado por algunos miembros del clero,
para hacer que los Amigos y sus principios fueran odiosos para el mundo.
Sus tergiversaciones fueron refutadas y sus astutos artificios puestos de manifiesto,
por Joseph Wyeth y George Whitehead en un libro titulado [.book-title]#A Switch for the Snake.#
(Un Golpe para la Serpiente)]
y algunos otros nos querían hacer creer.
Me llevé a Barclay conmigo a casa, y lo leí por completo en una semana,
excepto un pequeño tratado al final, que omití al considerarlo muy filosófico.

No obstante,
pronto leí lo suficiente como para convencerme de
mi propia ceguera e ignorancia en las cosas de Dios.
Pues al leerlo, descubrí que una luz irrumpía en mi mente,
y me refrescaba y consolaba poderosamente en aquel estado pobre,
bajo y humilde en el que estaba entonces; porque yo, en verdad estaba entonces,
y había estado durante un tiempo considerable, muy hambriento y sediento de justicia,
y por tanto, recibí la verdad con toda solicitud.
Fue como un bálsamo para mi alma,
y como lluvias para la tierra sedienta y reseca por el calor
y la sequía. Este autor expone las cosas tal claramente,
y las prueba con tal ingenio y destreza de conocimiento,
y me abrió las Escrituras con tal claridad, que sin pararme a criticar, disputar,
levantar argumentos u objeciones,
o consultar con '`sangre y carne,`' me rendí en seguida a Dios;
y llorando de gozo porque había encontrado un tesoro tan grande,
le agradecí muchas veces con lágrimas en los ojos
por tan bondadosa visitación de Su amor,
y que se hubiera complacido misericordiosamente a
mirar hacia mí cuando mi alma clamaba por Él. Y así,
aunque antes había tenido grandes dudas y aflicción
de mente al no saber qué camino tomar,
ahora encontraba que el sol irrumpía tan poderosamente sobre mí,
que las nubes estaban siendo dispersadas.
Ahora estaba completamente convencido en mi propia mente,
del camino que debía seguir y a qué pueblo me debía unir.

Así que dejé inmediatamente la comunión con la iglesia de Inglaterra,
y fui a la reunión en Gracechurch-street.
Después de leer a Barclay, leí algunos otros libros de ese tipo,
entre los cuales estaba una excelente pieza, aunque en un pequeño volumen,
llamada [.book-title]#No Cross, No Crown#.^
footnote:["`No Cruz, No Corona,`" por William Penn].
Continué leyendo
y frecuentando reuniones por varias semanas seguidas,
pero no dejé que nadie supiera lo que estaba haciendo.
George Whitehead fue el primer hombre con el que conversé; y eso,
varias semanas después de haber comenzado a leer
a Barclay y de asistir a los reuniones de los Amigos.
Por él llegué a conocerlos mejor, y cuanto más avanzaba,
más me gustaba la sencillez de ellos, y la decencia y simplicidad de sus conductas.
No usan las ceremonias y saludos de la iglesia de Inglaterra,
pero se dan la mano libremente,
y conversan como hermanos y hermanas que han brotado de la misma Simiente real,
y han sido hechos reyes y sacerdotes para Dios.
¡Oh, el amor,
la dulzura y el tierno afecto que he visto entre este pueblo! "`En esto,`" dice Cristo,
"`conocerán todos que sois mis discípulos, si tuviereis amor los unos con los otros.`"^
footnote:[Juan 13:35]
"`Vestíos, pues,`" dice el apóstol, "`como escogidos de Dios, santos y amados,
de entrañable misericordia, de benignidad, de humildad, de mansedumbre, de paciencia.`"^
footnote:[Colosenses 3:12]

Y así, mi querido amigo, te he dado cuenta de mis procedimientos en este asunto.
En cuanto a mi estado físico, si deseas saber cuál es,
puedo informarte que mi salud está tan bien como siempre,
y bendigo a Dios porque tengo suficiente comida y vestido para mí,
de manera que no carezco de ninguna cosa externa.
En realidad, tengo las necesidades y las comodidades de la vida,
así que no nos agobiemos con el cuidado de la vanidades y trivialidades de ella.
Poseamos nuestros vasos en santificación y honor;
y así como llevamos nuestras mentes a una perfecta sujeción a toda la voluntad de Dios,
llevemos nuestros cuerpos en la forma de vida más simple y natural.
Contentémonos con el menor número de cosas,
y no busquemos gratificar nuestros apetitos carnales,
ni seguir las costumbres e indulgencias de los hombres; busquemos más bien,
cómo gobernar nuestros intereses y placeres terrenales
de tal manera que podamos llevar mayor gloria a Dios,
mayor salud y paz a nuestras propias almas, y hacer el mayor servicio a la Verdad.
Y si este es nuestro objetivo, entonces,
ciertamente nos bastará una muy pequeña porción de las cosas de este mundo.
Viendo que somos Cristianos, debemos, por tanto,
perseguir con ahínco aquellas cosas que nos acercan a Dios.
Porque todo lo que es más que una necesidad, parece ser una carga para el alma,
cuyo deseo es respirar en una vasija pura,
para así tener un sentido vivo y saborear todas las bendiciones,
tanto del mundo superior como del inferior.

Tú sabes, mi querido amigo, que la religión es algo muy serio.
El arrepentimiento es una gran obra,
y una preciosa alma inmortal es de más valor que diez mil mundos que perecen,
con toda la pompa y gloria de ellos.
Por tanto, tengamos valor y seamos valientes por la verdad en la tierra.
No nos contentemos con un nombre y una profesión de la piedad,
sino vengamos a la vida y al poder de esta,
sin renunciar nunca a nuestra esperanza de obtener la victoria.
Nosotros tenemos un poco de fuerza de Dios; seamos fieles a Él y Él nos dará más fuerza,
para que así veamos al enemigo de nuestra paz caer delante de nosotros,
y nada sea imposible para nosotros.
Digo, amigo mío, seamos fieles a esa medida de luz y conocimiento que Dios nos ha dado,
para ser beneficiados y edificados por ella en la vida espiritual.
Y en la medida que Dios vea que somos diligentes
y fieles para obrar con la fuerza que hemos recibido,
Él nos iluminará más y más,
y veremos el fin de esas formas y sombras de religión en las que vivíamos antes.
Pero si Él ve que buscamos descansar en esas sombras,
o que nos volvemos fríos e indiferentes en la búsqueda de santidad,
corriendo hacia conceptos y especulaciones,
y que tenemos más disposición a disputar y a tener la apariencia de aprendizaje y sutileza,
que a llevar un vida santa y devota,
entonces es justo que Dios nos deje en un estado carnal y contaminado.
De esta manera continuaremos sólo en el atrio exterior,
donde podemos complacernos contemplando la belleza
y los ornamentos de un santuario mundano,
y nunca experimentaremos la eliminación del velo,
ni el ser llevados por la sangre de Jesús al lugar santísimo,
el único lugar donde hay verdadera paz con Dios y reposo para el alma cansada.
Podría decir mucho sobre este tema, si el tiempo o la libertad me lo permitieran.

En cuanto a una respuesta más detallada a tu carta, no tengo tiempo ahora para darla,
pero deseo que por el momento esta respuesta general sea suficiente.
Y si consideras las cosas en su naturaleza pura,
y no permites que el prejuicio de la educación te influya,
sino que en temor y humildad escudriñas la verdad por ti mismo,
encontrarás que no hay necesidad de otra respuesta para tu carta que la que ya he dado.
Porque al esperar en Dios y buscarlo diligentemente,
encontrarás una respuesta en tu propio corazón; y esta será más completa,
clara y satisfactoria que la que yo, o cualquier otro hombre viviente,
pueda intentar darte.
Pues verdaderamente deseo que tú,
junto con todos los de corazón sincero en la iglesia de Inglaterra,
lleguen a experimentar el omnipotente poder de Dios que los salva y redime de todo yugo;
y puedan claramente ver "`el fin de aquello que había de ser abolido,`"^
footnote:[2 Corintios 3:13]
y llegar al deleite de las cosas espirituales y celestiales.
En verdad, Dios sabe que esta es la oración diaria y profundo anhelo de mi alma.

Hasta que pueda entrar más en los detalles, si te place,
puedes comunicar esto a los demás y hacerles saber que estoy bien,
y agradéceles sus amables cartas.
Recordemos orar unos por otros con todo fervor,
para que podamos mantenernos perfectos en toda la voluntad de Dios.
Mi alma dice, Amén.

[.signed-section-closing]
Tu más afectuoso amigo y siervo en Jesús,

[.signed-section-signature]
Samuel Crisp.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Carta II

[.salutation]
Mi querido amigo,

Recientemente recibí tu carta amable y fraternal, por la que te devuelvo mucha gratitud.
Ahora estoy en comunión con el pueblo llamado Cuáqueros,
y tengo motivos para bendecir a Dios por este feliz cambio en mi vida.
Por misericordia, he sido sacado de la sombra de la religión,
y me estoy esforzando por conocer el poder, la vida y la virtud vivificantes de esta,
a fin de ser un Cristiano de verdad y no sólo de nombre
y profesión. Por mucho tiempo hablé y discutí sobre santidad,
y sin embargo, no entendía lo que era caminar con Dios, vivir y habitar en Él. De hecho,
tal vez algunos piensen que tuve la apariencia de piedad cuando estaba con ustedes;
¡pero ay!--estaba profundamente consciente de mis propias faltas y errores, y resolví,
con la ayuda de Dios,
buscar algo más noble y excelente que lo que había descubierto en ese estado.
Y bendito sea Su nombre para siempre, Dios ha respondido al clamor de mi alma,
y me ha permitido ver a un pueblo que es odiado y despreciado por el mundo,
pero amado para Él; pues Él les ha revelado los misterios del reino.
Los ha llevado sobre alas de águilas y cuidado como a la niña de Sus ojos.

En cuanto a mí, hasta ahora sólo he estado en el atrio exterior,
y muy lejos de esa verdad y justicia que es enseñada y practicada entre este pueblo;
porque ellos han entrado al lugar santísimo.
En efecto, han entrado en una comunión cercana con Dios,
y contemplan los querubines de gloria que cubren el propiciatorio,
y son alimentados con el verdadero maná. Estos misterios son revelados al manso y humilde,
pero los altivos, insolentes y profanos no pueden acercarse a ellos,
ni gustar su dulzura o consuelo.
El tipo de gente formal y tradicional del mundo puede hablar de estas cosas,
según las han oído de otros,
y en sus momentos sobrios pueden tener algunos tenues vislumbres de ellas;
pero están tan lejos de poseer el disfrute real e interior de ellas,
como de realizar las mayores imposibilidades.
En realidad, todo el ingenio, sutileza y conocimiento de estas personas,
no pueden llegar lo suficientemente alto como para tocar la Palabra de vida;
porque Esta sólo la conocen aquellas que están contentas
de abandonarlo todo y convertirse en tontas por Cristo.
Sí,
sólo estas personas están en buena disposición de recibir
y cooperar con las influencias del Espíritu Santo,
tras haber visto el vacío y la vanidad de todas esas
cosas que son tan admiradas por el mundo.
Las escuelas y universidades, los sabios doctores y grandes rabinos,
no me han servido de nada,
porque se han apartado del Espíritu de Dios y adentrado en sus propios conceptos y especulaciones,
pensando que con ello podían buscar a Dios y comprender la verdad.
¡Ay! --los misterios del reino están fuera del alcance de sus mentes carnales;
se cansan en vano, porque el ojo de buitre no puede penetrar en esos secretos.
Todos los grandes críticos, eruditos y filósofos del mundo son tontos en estas cosas.
Se cansan tratando de descubrir las cosas profundas de nuestro Dios,
estudiando y devanándose los sesos,
dando vueltas y tumbos de un lado a otro como un toro salvaje en una red,
que no sabe cómo desenredarse a sí mismo--que cuanto más lucha,
más se cansa y más fuertemente se ata.
Así también, cuanto más leen estos vanos habladores, cuanto más escriben,
cuanto más cavilan y disputan, más lejos están de Dios,
más manifiestan su odio y enemistad al Espíritu de Cristo y a la simplicidad del evangelio.

Durante mucho tiempo he estado cansado de la insensatez e impertinencia de estos hombres,
y principalmente de los célebres "`padres de la iglesia,`" como los llaman ellos.
Los concilios y sínodos de antaño,
ahora tienen muy poca importancia para mí. No me avergüenza
sentarme bajo las enseñanzas de mujeres y mecánicos,
sin importar lo que parezcan a los ojos del mundo; porque ciertamente,
ellos me enseñan ahora más Cristianismo,
y me instruyen más perfectamente en la vida divina,
que todos los estudiados y elaborados sermones y
discursos que alguna vez oí en las universidades,
o he oído desde entonces.
Las palabras de ellos son poderosas; en efecto,
ellos son poderosamente asistidos por el Espíritu de Dios,
y hablan con majestad y autoridad, y hay una belleza nativa,
claridad y solidez de expresión que brilla a través de sus discursos,
que es suficiente para responder a esa calumnia infundada, a saber,
que la predicación de los Cuáqueros es tontería, y que nadie puede entenderlos.
Esto a menudo ha sido refutado por muchos testimonios vivos que he oído,
de modo que los considero las mejores mentes y la gente más sagaz en el mundo;
porque ellos emplean sus habilidades y conocimientos en el temor de Dios,
para Su gloria y servicio, y para promover el verdadero interés de la humanidad.

En cuanto a las pequeñas y comunes bromas,
los comentarios chistosos, y la vana ostentación de la época,
que sé que el mundo estima (y nada lo complacerá sino lo que abunda en tales tonterías),
digo, si los Cuáqueros son deficientes en algo de esto, no es por falta de habilidades,
o porque tengan menos ingenio que otros hombres,
sino porque tienen más prudencia y sabiduría para gobernarlo.
Esa es la razón por la que ellos evitan esas vanidades infantiles,
que son tan libremente usadas y consentidas por otros,
para la gran deshonra de Dios y de la religión Cristiana.
Por tanto,
debido a que ellos no buscan complacer a los hombres de esta época liviana y desvergonzada,
ni hacer que la gente se ría y se alegre,
ni tampoco entretener a esa mente carnal y superficial con historias agradables,
conceptos finos y expresiones ingeniosas de las cosas naturales,
es que han sido vergonzosamente tergiversados por el mundo como las personas más ignorantes,
ciegas y tontas que alguna vez hayan hecho alguna profesión religiosa.

Sin embargo, este es el pueblo al que ahora me he unido en sincero amor a la verdad;
y Dios sabe,
que me glorío más en esta comunión y conocimiento de estos corderos de Cristo,
que si estuviera relacionado con los más grandes reyes,
señores y potentados de la tierra.
Mi espíritu se ha refrescado muchas veces con los de ellos,
cuando nos hemos reunido a esperar en Dios;
y mi alma anhela y suspira ser llenada aún más de esos consuelos divinos.
Él siempre está dispuesto a derramar bendiciones sobre nosotros,
si nos preparamos para recibirlas,
y si dejamos los vanos pensamientos que nublan y oscurecen la mente,
y estorban así las influencias e iluminaciones beneficiosas del cielo.
Y ya que le ha placido a Dios visitarme últimamente,
y darme a conocer excelentes cosas en la justicia,
sólo Él debe recibir la alabanza y la gloria de todo;
y ahora me rindo voluntariamente a la guía del bendito Espíritu.

Y ahora,
¡qué prospere la verdad! ¡Qué corra y sea glorificada
en la tierra! ¡Qué brille con todo su esplendor,
para el terror y confusión de todos sus enemigos,
y para reanimación de las almas de los hambrientos
y sedientos que están a punto de desfallecer,
esperando y deseando la consolación de Israel,
hasta que llegue de la presencia del Señor el tiempo de refrigerio!
Ciertamente, Él abrirá una fuente para Judá y Jerusalén,
y correrán ríos en los lugares secos, y ahí hablará paz a Su pueblo.
Y después de que se hayan sentado en el polvo por un rato en silencio,
permitiendo pacientemente que Su vara castigadora de amor trate con ellos,
Él consolará a la hija de Sion y dirá: "`¡Levántate, afligida,
y no llores ni te lamentes más, sino vístete con tus hermosos vestidos, oh,
Jerusalén! ¡Levanta tu cabeza, descubre tu rostro y ciñe tus lomos con fuerza;
mira el amanecer y cómo se esparce la mañana sobre las montañas;
porque ya han pasado las dolorosas noches de aflicción,
las nubes se han dispersado y se han ido,
el sol ha salido en su resplandor y ahora el gozo y la paz serán multiplicadas!
'`Con un poco de ira escondí Mi rostro de ti por un momento;
pero con misericordia eterna tendré compasión de ti, dice Jehová tu Redentor.`'`"

Oh, esperemos entonces con humildad de alma y ternura de corazón delante del Señor,
que podamos experimentar este gran cambio y salvación obrados en nosotros y para nosotros,
para que la Escritura no sea más un libro sellado para nosotros,
sino que podamos _sentir_ que la preciosa verdad en ella registrada se cumple en nosotros.
Entonces, nunca nos cansaremos de orar y leer las Sagradas Escrituras;
nunca tendremos miedo o estaremos renuentes a entrar en la presencia de Dios;
porque Su amor y la dulzura de Su ungüento nos atraerá
y seducirá para que moremos siempre bajo Su dosel,
y podamos sentir el fluir de la vida y del poder de Aquel que es
el océano que suple todas las necesidades de los hijos de los hombres.
Y, ¿cómo llegaremos a probar ese banquete celestial que Él ha preparado para nosotros,
el que podemos comer y beber en Su mesa, y nuestras almas deleitarse en la grosura--digo,
cómo llegaremos a esto, sino mediante una vida estricta y entregada a la cruz?
Ciertamente, cuánto más nos retiremos de los goces mundanos,
y nos vaciemos de las comodidades terrenales y falsos deleites,
más aptos seremos para recibir lo espiritual y celestial;
y no sólo para recibirlo y regocijarnos en ello por un tiempo,
sino para vivir y morar allí para siempre.
Porque esta es la vida de Jesús,
y en ella reina el reino de Dios en el corazón y en el alma,
mediante la cual '`somos transformados de gloria en gloria,
como por el Espíritu del Señor.`'

Y ahora les quiero preguntar a todos los sabios y prudentes, a todos los ricos,
a todos los hombres nobles y eruditos del mundo, ¿qué piensan de estas cosas?
¿Pueden aprenderse estas cosas en sus cortes y palacios?
¿Pueden proveernos de un sistema de divinidad como este,
los grandes académicos y las grandes universidades en la Cristiandad?
No; ellos lo odian y lo desprecian; y en lugar de una respuesta sobria a mi pregunta,
me devuelven burla y menosprecio.
"`Esto es balbuceo,`" dicen,
"`un sueño inútil y un engaño forjado en su propio cerebro;`" y muchos
más términos injuriosos les han dado a indagaciones como estas.
A veces, tal vez, suavicen sus expresiones con una demostración hipócrita,
pretendiendo compadecerse de mí y llamándolo un infeliz
efecto de la melancolía y del excesivo alejamiento del mundo.
Otros piensan que esto es demasiada condescendencia,
y que yo debería agradecerles que le den un calificativo tan suave;
porque en otros momentos tratan con más dureza, y confiadamente dicen que es locura,
engaño, brujería y fanatismo diabólico.
Pero estoy contento de estar bajo todas esas odiosas afirmaciones del mundo,
sabiendo muy bien, que hombres mejores que yo han sufrido lo mismo antes que yo,
y lo sufren en este tiempo.
En cuanto a mis enemigos, puedo decir en verdad,
que le agradezco a Dios poder compadecerme de ellos y orar por ellos; no me hacen daño,
sino a sí mismos.

Y ahora mi querido amigo, antes de terminar,
permíteme hablar un poco de tus circunstancias actuales; porque como Dios sabe,
mi corazón se conmueve por ti en el tierno amor de
Jesús. Supongo que ahora estás donde te dejé,
con lord Richardson (así llamado),
en calidad de capellán--un oficio del que yo mismo he tenido
un poco de experiencia desde la última vez que te vi,
pero me cansé tan rápido de ese yugo servil,
y me sentía tan indigno de esa santa función que llevaba,
que renuncié a los diez días de mi nuevo privilegio,
y lo dejé sintiéndome más libre que cuando lo había emprendido.
Qué paz o satisfacción puedes tener en esa clase de empleo, no lo sé; por mi parte,
no pude encontrar ninguna.
Mi alma se afligía y cargaba cada día, viendo y oyendo sus malas obras,
y contemplando sus vanidades y excesos.
En efecto, eso era como una espada para mi alma y para mi espíritu,
que me hería muy profundamente; y solemnemente confieso,
que prefiero pedir mi pan de puerta en puerta,
que vivir en semejante esclavitud otra vez,
donde estoy obligado a realizar ciertas ceremonias y formalidades,
halagar a los hombres en sus pecados, proclamar "`paz, paz`"^
footnote:[Jeremías 6:14, 8:11; Ezequiel 13:10, 16]
y "`coser almohadillas para todas las manos`"^
footnote:[Ezequiel 13:18 RVG, RV1602 Purificada]
de personas delicadas, que no soportan el menor freno o un ceño fruncido,
y en su lugar esperan que el sacerdote mercenario les ría o sonría en sus caras siempre,
incluso cuando él claramente ve que van para el infierno y la destrucción. Con todo,
debo decirte que la familia en la que yo estaba,
era considerada una de las más sobrias y estables, en lo que se refiere al mundo actual.
Debo decir también, que no los dejé porque percibiera que fueran dados a la bebida,
al juego o a maldecir; porque en cuanto a todas esas prácticas sucias y escandalosas,
hasta donde pude ver, eran irreprochables.
Sin embargo, vi que sus corazones no eran rectos,
porque eran amantes de los placeres más que de Dios; y tú sabes que él o ellos,
sean grandes o pequeños, si viven en los placeres,
se engordan y se despreocupan de Cristo; tales personas '`viviendo están muertas.`'^
footnote:[1 Timoteo 5:6]
Digo, cualquiera que sea su fe, o sus principios, o sus profesiones,
con respecto a la verdadera religión están muertos.

No diré nada más, sino que me apresuraré a terminar.
Si deseas un relato detallado de mi convencimiento,
puedes verlo en una carta que le escribí recientemente a Richard Lake, hijo,
en la que le hice un relato justo y verdadero de mi proceder en ese asunto,
los pasos que di, y cómo me ayudó Dios misericordiosamente,
tras haber levantado en mí sinceros deseos e inquietudes en pos de la verdad y la santidad.
Querido amigo, no tengo más por el momento,
sino hacerte saber que oro de todo corazón por ti,
pidiendo que puedas considerar estas cosas sin prejuicios,
y que no permitas que ninguna de las tentaciones
y atracciones del mundo aparten tu mente de Dios,
y te estorben en tu búsqueda de la santidad.
El que ama a padre o madre, hermano o hermana, o cualquier tesoro de este mundo,
más que a Cristo,
no es digno de Él. Pero si tú entras en comunión
con Cristo y sigues la guía de Su luz y Espíritu,
¡oh, el bendito y feliz descanso que encontrarás para tu alma! ¡Oh,
los ríos de agua viva que brotarán en ti, de los que podrás beber gratuitamente,
y alabar a Dios por todas Sus misericordias y beneficios!
En efecto, que puedas a llegar a tales goces y refrigerios espirituales como estos,
es el sincero deseo de tu cordial y afectuoso amigo,

[.signed-section-signature]
Samuel Crisp.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Carta III

[.signed-section-context-open]
Leeds, 6 del mes Siete, 1702

[.salutation]
Amado amigo,

Te hago saber que el pasado cuarto-día se cumplió
una semana desde que llegué bien al final de mi viaje.
Pero aunque mi cuerpo ahora descansa en cuanto a lo externo,
todavía siento la necesidad de continuar mi viaje
interno y espiritual hacia la nueva Jerusalén,
la Canaán celestial, donde mi alma puede ser saciada con la eterna e inmutable felicidad.
Debo seguir vigilando,
para que el enemigo de mi alma no tome ventaja contra mí en ningún momento.
Debo seguir en guardia, continuar en la guerra del Cordero,
y diligentemente perseguir las cosas que hagan firme mi llamamiento y elección.
Creo que este es el estado de todo Cristiano mientras more en este mundo.
El reposo y la paz perfectos y completos sólo pueden esperarse
cuando hayamos dejado estos cuerpos mortales y frágiles,
y entremos en las mansiones de gloria que Cristo, nuestra Cabeza,
ha preparado para nosotros.
Pero si queremos reinar con Él en otro mundo, debemos sufrir con Él en este.
Si queremos usar la corona, primero debemos llevar la cruz.
Si queremos ser vencedores, debemos pelear.
Si queremos ganar el premio, no debemos ser perezosos e indiferentes,
sino emplear toda nuestra fuerza en la carrera cristiana.
En resumen, si queremos ser perfectos, debemos venderlo todo,
separarnos de todos nuestros amantes,
y sacrificar todos los placeres más cercanos y queridos que tenemos en este mundo.
Esto es negar el yo; en efecto, esto es hacer morir lo terrenal;
y este es ese arrepentimiento para vida, de que no hay que arrepentirse.
Mis saludos para tu tío y para tus Amigos.

[.signed-section-closing]
Tu cordial y afectuoso amigo,

[.signed-section-signature]
Samuel Crisp.

--

[.centered]
=== Extractos de la Vindicación del Pueblo Llamado Cuáqueros

[.centered]
de Samuel Crisp.

+++[+++El primero de los dos fragmentos que se presentan a continuación,
está sacado del Prefacio de [.book-title]#La Vindicación# de Samuel Crisp,
y el segundo está tomado del propio tratado.
Se cree que el consejo de peso, la doctrina sana,
e instructivas observaciones que contienen estos fragmentos,
se recomendarán a sí mismas a la cordial aceptación de cualquier lector serio.]

[.centered]
==== Una Alegato a Favor de la Verdad, y una Ferviente Exhortación a ser Hallados Caminando en Ella.

[quote.scripture, , Jeremías 6:16]
____
"`Paraos en los caminos, y mirad, y preguntad por las sendas antiguas,
cuál sea el buen camino, y andad por él,
y hallaréis descanso para vuestra alma.`"
____

[.salutation]
Lector,

Deseo que seas serio e imparcial en la lectura de lo que aquí presento ante tu vista,
para que puedas obtener beneficios y ventajas para tu alma.
El ruido y el clamor contra los Cuáqueros, en los últimos años,
han sido llevados a cabo y promovidos con gran diligencia por sus adversarios;
de manera tal, que pocos, creo yo, que conversen con el mundo pueden ignorarlo.
Esto me dio la oportunidad de investigar sus principios;
y a fin de no tomar las cosas sin examinar,
ni creer el informe de otros con respecto a ellos, me dispuse a ver por mí mismo,
a leer y a consultar a sus propios autores.
Me dediqué a esto con gran seriedad,
pidiéndole al Señor (en gran humildad y sumisión de alma)
que abriera mi entendimiento a las grandes cosas de Su ley,
y que si la verdad estaba entre los Cuáqueros, yo pudiera,
sin consultar con '`carne y sangre,`' unirme a ese pueblo,
por mucho que me despreciara y repudiara el mundo por hacerlo.
Yo quería paz con Dios; y en comparación con esta,
consideraba todas las otras cosas como escoria y estiércol.

Fui educado en la forma nacional de culto,
y era más estricto y puntual que muchos en los ritos y ceremonias de la iglesia de Inglaterra;
sin embargo, encontraba que todo eso no servía, porque la Semilla estaba oprimida,
y la muerte todavía reinaba bajo todas esas formas y apariencias externas de piedad.
Era fácil hablar y hacer la ronda de mis devociones,
pero yo carecía de fuerza y poder para vencer mis pecados y corrupciones.
Un clamor se levantaba en mi alma en busca de la justicia y la verdad,
y encontré que todo lo que yo cumplía externamente no podían darlas,
porque el reino de Dios está dentro de los hombres, aunque yo lo buscaba afuera,
pues estaba muy embelesado de las sombras.
De esa manera era desviado de la búsqueda del conocimiento de la verdad,
como está en Jesús. Yo vivía en tinieblas e ignorancia
del verdadero y salvador conocimiento de Dios,
a pesar de mis altivas pretensiones.
Pero le plació a Dios rasgar el velo,
y en una buena medida dispersar las nubes y esparcir las brumas y neblinas;
bendito sea Su nombre.

Quiero que sepas, lector,
que hay un pueblo en esta época que ha pagado algo por la religión;
y que ellos no se dejarán engañar con farsas ni con pretensiones,
ni se dejarán seducir por las artimañas del enemigo.
No son fáciles de engañar en las cosas importantes que conciernen a su paz eterna.
No pueden inclinarse ante imágenes,
ni satisfacerse con las cáscaras y formalidades de la religión,
sino que se esfuerzan por llegar a la vida de santidad y a la práctica real de la virtud,
y ni las sonrisas ni los ceños fruncidos pueden prevalecer
sobre ellos para que abandonen la verdad.
El diablo los envidia, y para hacerlos odiosos, los pinta de negro.
Ciertamente, según él son tontos, locos, fanáticos, cismáticos, herejes,
una clase peligrosa de gente.
"`Señores,`" dicen, "`mírense a sí mismos y como aman sus almas,
cuídense de la infección del Cuaquerismo.`"
Este es el lenguaje común siempre que un pueblo no complace al diablo;
pero si son pasivos y abiertos a sus insinuaciones,
si pueden descansar en una forma externa, y quedarse en palabras y conceptos,
entonces él reina en paz; su reino está tranquilo y no se necesitan nombres duros.

Bien, lector, lo que dije antes lo repito ahora: te concierne a ti ser serio,
y sopesar las cosas con una mente clara e imparcial.
Si quieres servir a Dios, debes animarte y desprenderte del mundo.
Si quieres venir a Cristo, encontrarás verdaderas riquezas y una fuente de gozo inefable.
Si mueres con Cristo, vivirás; si sufres con Cristo en este mundo vano y transitorio,
reinarás con él en gloria para siempre.
No mires tu propia debilidad, sino a Dios, cuya gracia es suficiente para ti;
Su fuerza se engrandece en nuestra debilidad.
Por tanto, no dejes que la cruz te desanime, sino tómala,
y en mansedumbre y paciencia llévala en pos de Jesús,
quien por el gozo puesto delante de Él sufrió la cruz, menospreciando el oprobio,
y se sentó a la diestra del trono de la Majestad en los cielos.
Despójate de las cosas creadas; destétate de tus afectos terrenales;
fortalece tus manos en Dios; aférrate firmemente a Él. Haz de Él tu amigo,
y entonces no te importará quien sea tu enemigo;
toda la furia de los hombres y demonios no podrá
hacerte daño. Escucha a Dios y obedece Su voz;
presta atención a las enseñanzas de Su Espíritu Santo y entrégate por completo a Su guía,
porque Sus caminos son caminos deleitosos y todas Sus veredas paz.
Este es el Consolador que nos es dado para guiarnos a toda verdad,
y bendito todos aquellos que son enseñados y guiados
por Él. A estos se les permite ver su propio camino;
se les aclara y su brillo va en aumento hasta que el día es perfecto.
No te confíes a las incertidumbres, ni pospongas tu arrepentimiento;
no retrases el momento de volverte a Dios, porque,
¿cómo sabes si vivirás una hora más? ¿Son justas y claras todas tus cuentas?
¿Estás listo para partir si Dios te llamara antes de mañana por la mañana?

Lector, una vez más digo: te concierne ser serio, porque el día de Dios se apresura,
en el que todas las falsas cubiertas serán arrancadas.
El temor se apoderará de los hipócritas como se apodera
el dolor de una mujer que está de parto,
y no escaparán. El nombre y la profesión del Cristianismo sin la vida y el poder de este,
serán entonces de muy poca ventaja.
De hecho, será un día terrible, y ¿quién podrá resistirlo?
Ciertamente, ninguno de los hipócritas, ni los que arrastran los pies cuando saludan,
ni los que hablan vanidades, ni los disputadores de este mundo;
ninguno de los especuladores huecos, ni los que fingen,
ni los que complacen a los hombres; no; todos estos serán barridos como paja al viento.
"`Porque he aquí, viene el día ardiente como un horno,
y todos los soberbios y todos los que hacen maldad serán estopa;
aquel día que vendrá los abrasará, ha dicho Jehová de los ejércitos,
y no les dejará ni raíz ni rama,`" Malaquías 4:1. Por tanto, este es el tiempo aceptado,
aprécialo.
Ahora es el día de salvación.

Por tanto, debes saber, lector, que por la gracia de Dios eres capaz de grandes logros.
La verdadera fe moverá montañas,
y por medio de ella puedes escapar de las contaminaciones del mundo,
salir limpio de Babilonia y de Egipto,
y de todas las cosas que te frenarían y estorbarían en tu carrera cristiana.
¿Por qué deberíamos entonces malgastar nuestros preciosos minutos?
¿Por qué deberíamos morir sin alcanzar la verdadera felicidad?
¡Qué el tiempo pasado nos baste para haber hecho la voluntad de los gentiles,
sirviendo a diversos deseos y placeres, y caminando en la vanidad de nuestras mentes!
Dios nos ha soportado mucho tiempo; Su misericordia y amorosa bondad han sido grandes.
No lo provoquemos más,
sino volvámonos inmediatamente a Él y humillemos nuestras almas
delante de Él. Esta es la labor y el esfuerzo de mi alma,
Dios lo sabe,
que todos los hombres se salven y lleguen al conocimiento de la verdad como está en
Jesús. ¡Ojalá todos probaran y vieran cuán bondadoso es Él! Si esperaran en Él en silencio,
con sus mentes retiradas del mundo y fijas en Él,
llegarían a ver cosas maravillosas en la justicia.
Sí, los misterios del reino de Dios les serían abiertos y revelados;
cosas que han sido guardadas en secreto desde la fundación del mundo.
Los tales encontrarían la verdadera paz y reposo para sus almas.
Ellos encontrarían que les son administradas fuerzas según sus diversas necesidades,
y gracia para ayudarlos en tiempo de necesidad; sí,
irían de poder en poder y crecerían en gracia todos los días,
como lo dice el apóstol en Efesios 4:13,
"`Hasta que todos lleguemos a la unidad de la fe y del conocimiento del Hijo de Dios,
a un varón perfecto, a la medida de la estatura de la plenitud de Cristo.`"
Que todos lleguemos a conocer, atestiguar y experimentar esto en nosotros mismos,
es la ferviente súplica y oración de tu bien intencionado y sincero amigo,

[.signed-section-signature]
Samuel Crisp.

[.centered]
==== Sobre la Adoración Divina, el Ministerio del Evangelio y la Iglesia Verdadera.

[quote.scripture, , John 4:24]
____
"`Dios es Espíritu; y los que le adoran,
en espíritu y en verdad es necesario que adoren.`"
____

Nuestra creencia Cristiana,
es que todo hombre debe esperar en Dios en la medida de Su buen Espíritu;
y que debe seguir Sus movimientos, observar Sus consejos,
y hacer de Él su gran regla y guía de su vida.
En la medida que los hombres esperan en este Espíritu,
y son conducidos y gobernados por Él,
así (y no de otra manera) son aceptados y aprobados ante los ojos de Dios.
Porque esto, y sólo esto,
puede producir todas las obras aceptables en nosotros y por nosotros.
"`Andad en el Espíritu, y no satisfagáis los deseos de la carne.`"
Gálatas 5:16. "`Porque todos los que son guiados por el Espíritu de Dios,
estos son hijos de Dios.`"
Romanos 8:14. En la realización de toda adoración religiosa,
decimos que hay una necesidad especial de que los hombres esperen en Dios,
en el don de Su Espíritu, para sentir la guía y ayuda de Él;
porque esta es la sal del sacrificio que da sabor y vida a cada deber.
Solo este Espíritu puede darnos a conocer nuestras verdaderas necesidades,
e instruirnos en cómo presentarnos ante Dios para el oportuno alivio.
El apóstol de los gentiles tiene este excelente dicho:
"`Y de igual manera el Espíritu nos ayuda en nuestra debilidad&hellip;Mas
el que escudriña los corazones sabe cuál es la intención del Espíritu,
porque conforme a la voluntad de Dios intercede por los santos.`"
Romanos 8:26-27 Dios debe ser adorado en espíritu y en verdad, y por tanto,
esperamos en Él en silencio para poder realizar esta adoración y servicio,
creyendo que Su Espíritu nos ayudará y enseñará a orar mejor que todas
las guías y libros de oración común. ¿Debemos ser ridiculizados por esto?
Y porque somos tiernos con la Semilla justa de luz y vida en nosotros mismos, y en otros,
guardando lo que el apóstol ordena--no apagar al Espíritu ni despreciar
la profecía--¿debemos ser llamados fanáticos y apasionados?

No es que los hombres repasen sus oraciones de memoria, o que las lean de un libro,
o que se empeñen en orar o predicar con la fuerza de su propia razón y facultades naturales,
lo que encuentra aceptación de Dios.
Nada de estos puede considerarse como esa adoración y servicio
espiritual que Dios pide en los días del evangelio,
ahora que Él ha enviado al Espíritu de Su Hijo a
nuestros corazones por el que clamamos Abba Padre.
No ahora, digo,
cuando Él ha derramado a Su Espíritu sobre los hijos
y las hijas para que puedan y deban profetizar.
No ahora, cuando Dios se ha revelado tan claramente al mundo,
y nos ha dicho expresamente por Su Hijo que Él es Espíritu,
y que los verdaderos adoradores lo adorarán en espíritu y en verdad,
y que Él busca a estos para que lo adoren.
Estos son los días del _Evangelio._
Esta es la última y más gloriosa dispensación que habrá alguna vez en el mundo;
y Dios pide ahora un rigor y una pureza de vida más que ordinarios.
"`Pero Dios,`" se dice, "`habiendo pasado por alto los tiempos de esta ignorancia,
ahora manda a todos los hombres en todo lugar, que se arrepientan;`"^
footnote:[Hechos 17:30]
que dejen sus formas muertas, sus ceremonias vacías y su hipócrita culto voluntario,
un culto que pueden realizar en su propio tiempo,
comenzándolo y terminándolo a su placer.
Aquí muchos están haciendo una profesión de religión y de piedad externamente,
siguiendo un ciclo de ceremonias corporales y devociones fingidas de un año a otro,
y sin embargo, están destituidos del conocimiento interno y vivencial de Jesucristo.

Pero bendito sea Dios para siempre,
porque en esta generación ha desnudado Su brazo de manera maravillosa y ha acercado
a un remanente a Él. Estos han visto el fin de los tipos y sombras,
y han llegado a Cristo, la vida y la sustancia,
y al único bautismo espiritual que purga la consciencia
de obras muertas para servir al Dios vivo.
Y han llegado a la verdadera cena,
y a la comunión interna del cuerpo y de la sangre de Cristo,
donde son alimentados diariamente en Su mesa,
y comen del pan que bajó del cielo y que nutre al alma para vida eterna.
Estos han sido apartados de todos los maestros carnales y literales del mundo,
y han llegado a la ministración del Espíritu y a las enseñanzas de Jesucristo,
quien es el Profeta, Sacerdote y Rey de ellos,
el único verdadero Pastor y Obispo de sus almas.
Estos han llegado a un verdadero silencio, y cesado de sus propias palabras;
esperan el surgimiento del Poder y la Vida divinos que harán que su servicio
sea aceptable para Dios y útil y beneficioso para los hombres.
Predican y oran según el Espíritu los ayuda.
Guardan la regla y precepto de Cristo, que es, "`velad y orad;`"^
footnote:[Mateo 26:41; Marcos 13:33, 14:38; Lucas 21:36]
el cual, claramente muestra que antes de que los hombres oren, deben velar; es decir,
retirar sus mentes y esperar en Dios,
para que puedan servir "`a Dios agradándole con temor y reverencia;
porque (como dice el apóstol) nuestro Dios es fuego consumidor.`"

Aquellos que se apresuran a entrar en Su presencia,
sin la debida preparación y vigilancia, "`ofrecen el sacrifico de los necios;`"^
footnote:[Eclesiastés 5:1]
ellos no '`son ofrecidos con agrado en el altar de Dios.`'^
footnote:[Isaías 60:7]
Se dice de Nadab y Abihu, que "`ofrecieron delante de Jehová fuego extraño,
que él nunca les mandó. Y salió fuego de delante de Jehová y los quemó,
y murieron delante de Jehová.`"^
footnote:[Levítico 10:1-2]
¡Que los impíos e incircuncisos sacerdotes y personas del mundo--que en
toda ocasión están llenos de sus oraciones y devociones--consideren esto!
Estoy seguro de que se avergonzarían de presentarse ante alguno de sus superiores
en la postura con la que muchas veces se presentan delante de Dios.
Pero, como dije antes, los que conocen a Dios correctamente,
han aprendido a esperar en Él en el silencio de toda carne.
"`Porque separados de mí,`" dice Cristo, "`nada podéis hacer.`"^
footnote:[Juan 15:5]
Al estar profundamente conscientes de esto,
han aprendido a inclinarse y a humillarse delante de Dios;
sin atreverse a abrir sus bocas o decir una palabra,
excepto en la medida que Dios se plazca en darles a conocer los misterios de Su reino,
para prepararse un sacrificio para Él mismo,
y tocar los labios de ellos con una carbón vivo del altar.
Cuando el pozo brota, _entonces_ pueden cantarle (Números 21:17). Cuando Dios abre,
nada puede cerrar; y cuando Él cierra, nada puede abrir.
Por tanto, estos esperan, como lo hicieron los apóstoles en Jerusalén,
para recibir el poder de lo alto.
Y cuando Dios les ordena hablar, deben hablar; no pueden añadir a lo que se les da,
ni quitar de ello.
No deben apagar al Espíritu, ni despreciar la profecía. (1 Tesalonicenses 5:19-20)

Esta es nuestra creencia Cristiana con respecto a la adoración
de Dios y a los solemnes oficios de la religión,
tales como orar y predicar.
Y por los pasajes citados,
todo ojo imparcial puede entender que estas no son "`nuevas
luces`" o "`conceptos novedosos,`" sino que están en concordancia
con las Escrituras y con la práctica de los Cristianos primitivos,
a cuyo bendito ejemplo, y vidas santas y piadosas,
deseamos conformarnos en todas las cosas.

La iglesia del Dios vivo es columna y baluarte de la Verdad.
Está edificada sobre el fundamento de los apóstoles y profetas,
del que Jesucristo mismo es la principal piedra del ángulo.
La iglesia se compone de piedras vivas, que son edificadas como una casa espiritual,
un sacerdocio santo,
para ofrecer sacrificios espirituales aceptables a Dios a través de Jesucristo.
Estas son un linaje escogido, un sacerdocio real, una nación santa, un pueblo adquirido,
quien en vida y conducta anuncian las virtudes de Aquel
que las llamó de las tinieblas a Su luz admirable.
Esta es una iglesia gloriosa, sin mancha, ni arruga, ni cosa semejante,
sino que es santa y sin tacha.
Esta es la verdadera iglesia y la verdadera religión,
que deseamos que todas las personas consideren seriamente y persigan diligentemente.

[.asterism]
'''

__Esta breve colección de cartas y escritos de Samuel
Crisp muestra que era un joven de sinceridad,
humildad y genuina piedad poco comunes.
No está claro si él fue llamado alguna vez a ministrar
públicamente en la Sociedad de Amigos,
pero se sabe que estuvo en compañía de ese estimado ministro, Samuel Bownas,
durante sus servicios al evangelio en el oeste de Inglaterra en el año 1702.
De él, Bownas escribe en su diario:
"`Tuve como compañero a un joven que había sido educado en la universidad,
su nombre era Samuel Crisp--un joven de espíritu agradable y apacible,
y correctamente convencido.
Era un dulce compañero,
que había recibido el conocimiento de la verdad de la manera correcta.`"
Tras haber comenzado a edificar sobre el único y seguro Fundamento,
es probable que muchos tuvieran la expectativa de que Samuel Crisp se
convertiría en un miembro útil para la iglesia de sus días. Pero cualquier
esperanza de este tipo sólo se cumplió en una medida muy limitada,
en vista de que le plació Al que dispone sabiamente los eventos, cortar su vida.
Él murió de viruela, en Stepney, al este de Londres, el 7 del mes Cuarto de 1704,
a los 34 años de edad.__
